- name: install and run nginx
  hosts: web
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.dnf:
      state: latest

    - name: run nginx
      ansible.builtin.service:
      state: present
      enabled: yes


