  - name: Multi play and run
    hosts: localhost
    tasks: 
    - name: task 1 and play1
      ansible.builtin.debug:
      msg: "Hello, this is from play1 and task1"

    - name: play2 and task2
      ansible.builtin.debug:
      msg: "Hello from play2 and task1"