- name: Variables
  hosts: web
  vars: #variable declaration
    COURSE: Devops and cloud
    TRAINER: Siva
  tasks:
  - name: printing through variables
    ansible.builtin.debug:
      msg: "Hello , am learning {{ COURSE }} from {{ TRAINER }}"