- name: Variables
  hosts: web
  vars: #variable declaration in play level
    COURSE: Devops and cloud
    TRAINER: Siva
  tasks:
  - name: printing through variables
    vars: #variable declaration in task level
      COURSE: Devops and cloud with 
      TRAINER: SivaKumar
    ansible.builtin.debug:
      msg: "Hello , am learning {{ COURSE }} from {{ TRAINER }}"