- name: Variables preceedence
  hosts: localhost
  vars_files:
    vars.yaml
  # vars_prompt:
  #   name: WISHES
  #   prompt: Enter your wishes
  #   private: false
  vars: #variable declaration in play level
    #WISHES: GM from play
  tasks:
  - name: printing through variables
    vars: #variable declaration in task level
      #WISHES: GM from task 
    ansible.builtin.debug:
      msg: "Hello , {{ WISHES }} "


# Variables preceedence:

  # 1. Variables given as arguments
	# 2. Variables given in task level
	# 3. Variables given in file
	# 4. Variables in prompt
	# 5. Variables in play
	# 6. Variables in inventory
  #   Variables in role level