- name: conditions
  hosts: web
  tasks:
  - name: using command module
    ansible.builtin.command: id expense
    ignore_errors: true

  - name: printing a message
    ansible.builtin.debug:
      msg: "Hello"