- name: conditions
  hosts: web
  tasks:
  - name: using command module
    ansible.builtin.command: id expense
    ignore_errors: true
    register: USER

  - name: Creating user
    ansible.builtin.command: useradd expense
    when: USER.rc != 0

  - name: printing a message
    ansible.builtin.debug:
      msg: "Hello {{ USER}}"