- name: Variables
  hosts: localhost
  vars:
    WISHES: GOOD DAY
  tasks:
  - name: printing through filters
    ansible.builtin.debug:
      msg: "Hello {{ WISHES | default ('GOOD Morning') }}"

  - name: printing in upper case
    ansible.builtin.debug:
      msg: "Hello {{ WISHES | upper }}"