- name: Variables
  hosts: localhost
  vars:
    WISHES: GOOD DAY
  tasks:
  - name: printing through filters
    ansible.builtin.debug:
      msg: "Hello {{ WISHES | default ('GOOD Morning') }}"

  - name: printing in upper case
    ansible.builtin.debug:
      msg: "Hello {{ WISHES | upper }}"

  - name: remove duplicates
    vars:
      numbers: [1, 3, 4, 5, 5, 6, 10, 10]
    ansible.builtin.debug:
      msg: "Hello {{ numbers | unique }}"

  - name: remove duplicates
    vars:
      numbers: [1, 3, 4, 5,  6, 10]
    ansible.builtin.debug:
      msg: "Hello , minimum number is:{{ numbers | min }} and maximum munber is  {{ numbers | max }}"

  - name: convert dict to items
    vars:
      BOOK_DETAILS: #dictionary/map
        Bookname: My Devops
        chapters: 20
        Pages: 100
    ansible.builtin.debug:
      msg: "Given Book details are {{ BOOK_DETAILS }}"
      msg: "Converted Book details are {{ BOOK_DETAILS | dict2items}}"