- name: Variables
  hosts: localhost
  tasks:
  - name: printing through filters
    ansible.builtin.debug:
      msg: "Hello {{ WISHES | default ('GOOD Morning') }}"

  - name: printing in upper case
    ansible.builtin.debug:
      msg: "Hello Mani | upper"